// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.5
// source: worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle state of a job.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_QUEUED      Status = 1
	Status_STATUS_ASSIGNED    Status = 2
	Status_STATUS_RUNNING     Status = 3
	Status_STATUS_SUCCEEDED   Status = 4
	Status_STATUS_FAILED      Status = 5
	Status_STATUS_CANCELED    Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_QUEUED",
		2: "STATUS_ASSIGNED",
		3: "STATUS_RUNNING",
		4: "STATUS_SUCCEEDED",
		5: "STATUS_FAILED",
		6: "STATUS_CANCELED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_QUEUED":      1,
		"STATUS_ASSIGNED":    2,
		"STATUS_RUNNING":     3,
		"STATUS_SUCCEEDED":   4,
		"STATUS_FAILED":      5,
		"STATUS_CANCELED":    6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

// Stable identifier for a registered worker node.
type WorkerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerID) Reset() {
	*x = WorkerID{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerID) ProtoMessage() {}

func (x *WorkerID) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerID.ProtoReflect.Descriptor instead.
func (*WorkerID) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Stable identifier for a submitted job.
type JobID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobID) Reset() {
	*x = JobID{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobID) ProtoMessage() {}

func (x *JobID) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobID.ProtoReflect.Descriptor instead.
func (*JobID) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *JobID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Resource requirements or availability snapshot.
type ResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	GpuCount      int32                  `protobuf:"varint,2,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceSpec) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceSpec) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ResourceSpec) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

// Minimal executable job definition for worker execution.
type Job struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobId             *JobID                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ContainerImage    string                 `protobuf:"bytes,2,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	Command           []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	RequiredResources *ResourceSpec          `protobuf:"bytes,4,opt,name=required_resources,json=requiredResources,proto3" json:"required_resources,omitempty"`
	Status            Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=compute.v1.Status" json:"status,omitempty"`
	CreatedAtUnix     int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *Job) GetJobId() *JobID {
	if x != nil {
		return x.JobId
	}
	return nil
}

func (x *Job) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *Job) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Job) GetRequiredResources() *ResourceSpec {
	if x != nil {
		return x.RequiredResources
	}
	return nil
}

func (x *Job) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Job) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

// Worker-reported job execution result.
type Result struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          *JobID                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status         Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=compute.v1.Status" json:"status,omitempty"`
	ExitCode       int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StdoutExcerpt  string                 `protobuf:"bytes,4,opt,name=stdout_excerpt,json=stdoutExcerpt,proto3" json:"stdout_excerpt,omitempty"`
	StderrExcerpt  string                 `protobuf:"bytes,5,opt,name=stderr_excerpt,json=stderrExcerpt,proto3" json:"stderr_excerpt,omitempty"`
	OutputUri      string                 `protobuf:"bytes,6,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`
	FinishedAtUnix int64                  `protobuf:"varint,7,opt,name=finished_at_unix,json=finishedAtUnix,proto3" json:"finished_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetJobId() *JobID {
	if x != nil {
		return x.JobId
	}
	return nil
}

func (x *Result) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Result) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Result) GetStdoutExcerpt() string {
	if x != nil {
		return x.StdoutExcerpt
	}
	return ""
}

func (x *Result) GetStderrExcerpt() string {
	if x != nil {
		return x.StderrExcerpt
	}
	return ""
}

func (x *Result) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *Result) GetFinishedAtUnix() int64 {
	if x != nil {
		return x.FinishedAtUnix
	}
	return 0
}

type RegisterWorkerRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AvailableResources *ResourceSpec          `protobuf:"bytes,1,opt,name=available_resources,json=availableResources,proto3" json:"available_resources,omitempty"`
	WorkerVersion      string                 `protobuf:"bytes,2,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterWorkerRequest) GetAvailableResources() *ResourceSpec {
	if x != nil {
		return x.AvailableResources
	}
	return nil
}

func (x *RegisterWorkerRequest) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

type RegisterWorkerResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId                 *WorkerID              `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterWorkerResponse) GetWorkerId() *WorkerID {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

func (x *RegisterWorkerResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type HeartbeatRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           *WorkerID              `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	AvailableResources *ResourceSpec          `protobuf:"bytes,2,opt,name=available_resources,json=availableResources,proto3" json:"available_resources,omitempty"`
	RunningJobs        []*JobID               `protobuf:"bytes,3,rep,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetWorkerId() *WorkerID {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

func (x *HeartbeatRequest) GetAvailableResources() *ResourceSpec {
	if x != nil {
		return x.AvailableResources
	}
	return nil
}

func (x *HeartbeatRequest) GetRunningJobs() []*JobID {
	if x != nil {
		return x.RunningJobs
	}
	return nil
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ServerTimeUnix int64                  `protobuf:"varint,2,opt,name=server_time_unix,json=serverTimeUnix,proto3" json:"server_time_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResponse) GetServerTimeUnix() int64 {
	if x != nil {
		return x.ServerTimeUnix
	}
	return 0
}

type RequestJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      *WorkerID              `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestJobRequest) Reset() {
	*x = RequestJobRequest{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJobRequest) ProtoMessage() {}

func (x *RequestJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJobRequest.ProtoReflect.Descriptor instead.
func (*RequestJobRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *RequestJobRequest) GetWorkerId() *WorkerID {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

type RequestJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasJob        bool                   `protobuf:"varint,1,opt,name=has_job,json=hasJob,proto3" json:"has_job,omitempty"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestJobResponse) Reset() {
	*x = RequestJobResponse{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJobResponse) ProtoMessage() {}

func (x *RequestJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJobResponse.ProtoReflect.Descriptor instead.
func (*RequestJobResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *RequestJobResponse) GetHasJob() bool {
	if x != nil {
		return x.HasJob
	}
	return false
}

func (x *RequestJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type SubmitResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      *WorkerID              `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Result        *Result                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultRequest) Reset() {
	*x = SubmitResultRequest{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultRequest) ProtoMessage() {}

func (x *SubmitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitResultRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitResultRequest) GetWorkerId() *WorkerID {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

func (x *SubmitResultRequest) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type SubmitResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultResponse) Reset() {
	*x = SubmitResultResponse{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultResponse) ProtoMessage() {}

func (x *SubmitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitResultResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\n" +
	"compute.v1\" \n" +
	"\bWorkerID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1d\n" +
	"\x05JobID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"e\n" +
	"\fResourceSpec\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tgpu_count\x18\x02 \x01(\x05R\bgpuCount\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x05R\bmemoryMb\"\x8f\x02\n" +
	"\x03Job\x12(\n" +
	"\x06job_id\x18\x01 \x01(\v2\x11.compute.v1.JobIDR\x05jobId\x12'\n" +
	"\x0fcontainer_image\x18\x02 \x01(\tR\x0econtainerImage\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12G\n" +
	"\x12required_resources\x18\x04 \x01(\v2\x18.compute.v1.ResourceSpecR\x11requiredResources\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.compute.v1.StatusR\x06status\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\"\x92\x02\n" +
	"\x06Result\x12(\n" +
	"\x06job_id\x18\x01 \x01(\v2\x11.compute.v1.JobIDR\x05jobId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.compute.v1.StatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12%\n" +
	"\x0estdout_excerpt\x18\x04 \x01(\tR\rstdoutExcerpt\x12%\n" +
	"\x0estderr_excerpt\x18\x05 \x01(\tR\rstderrExcerpt\x12\x1d\n" +
	"\n" +
	"output_uri\x18\x06 \x01(\tR\toutputUri\x12(\n" +
	"\x10finished_at_unix\x18\a \x01(\x03R\x0efinishedAtUnix\"\x89\x01\n" +
	"\x15RegisterWorkerRequest\x12I\n" +
	"\x13available_resources\x18\x01 \x01(\v2\x18.compute.v1.ResourceSpecR\x12availableResources\x12%\n" +
	"\x0eworker_version\x18\x02 \x01(\tR\rworkerVersion\"\x89\x01\n" +
	"\x16RegisterWorkerResponse\x121\n" +
	"\tworker_id\x18\x01 \x01(\v2\x14.compute.v1.WorkerIDR\bworkerId\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x02 \x01(\x05R\x18heartbeatIntervalSeconds\"\xc6\x01\n" +
	"\x10HeartbeatRequest\x121\n" +
	"\tworker_id\x18\x01 \x01(\v2\x14.compute.v1.WorkerIDR\bworkerId\x12I\n" +
	"\x13available_resources\x18\x02 \x01(\v2\x18.compute.v1.ResourceSpecR\x12availableResources\x124\n" +
	"\frunning_jobs\x18\x03 \x03(\v2\x11.compute.v1.JobIDR\vrunningJobs\"Y\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12(\n" +
	"\x10server_time_unix\x18\x02 \x01(\x03R\x0eserverTimeUnix\"F\n" +
	"\x11RequestJobRequest\x121\n" +
	"\tworker_id\x18\x01 \x01(\v2\x14.compute.v1.WorkerIDR\bworkerId\"P\n" +
	"\x12RequestJobResponse\x12\x17\n" +
	"\ahas_job\x18\x01 \x01(\bR\x06hasJob\x12!\n" +
	"\x03job\x18\x02 \x01(\v2\x0f.compute.v1.JobR\x03job\"t\n" +
	"\x13SubmitResultRequest\x121\n" +
	"\tworker_id\x18\x01 \x01(\v2\x14.compute.v1.WorkerIDR\bworkerId\x12*\n" +
	"\x06result\x18\x02 \x01(\v2\x12.compute.v1.ResultR\x06result\"2\n" +
	"\x14SubmitResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*\x9a\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_QUEUED\x10\x01\x12\x13\n" +
	"\x0fSTATUS_ASSIGNED\x10\x02\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x03\x12\x14\n" +
	"\x10STATUS_SUCCEEDED\x10\x04\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x05\x12\x13\n" +
	"\x0fSTATUS_CANCELED\x10\x062\xd2\x02\n" +
	"\rWorkerService\x12W\n" +
	"\x0eRegisterWorker\x12!.compute.v1.RegisterWorkerRequest\x1a\".compute.v1.RegisterWorkerResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.compute.v1.HeartbeatRequest\x1a\x1d.compute.v1.HeartbeatResponse\x12K\n" +
	"\n" +
	"RequestJob\x12\x1d.compute.v1.RequestJobRequest\x1a\x1e.compute.v1.RequestJobResponse\x12Q\n" +
	"\fSubmitResult\x12\x1f.compute.v1.SubmitResultRequest\x1a .compute.v1.SubmitResultResponseB\x14Z\x12coordinator/pkg/pbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_worker_proto_goTypes = []any{
	(Status)(0),                    // 0: compute.v1.Status
	(*WorkerID)(nil),               // 1: compute.v1.WorkerID
	(*JobID)(nil),                  // 2: compute.v1.JobID
	(*ResourceSpec)(nil),           // 3: compute.v1.ResourceSpec
	(*Job)(nil),                    // 4: compute.v1.Job
	(*Result)(nil),                 // 5: compute.v1.Result
	(*RegisterWorkerRequest)(nil),  // 6: compute.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 7: compute.v1.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),       // 8: compute.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 9: compute.v1.HeartbeatResponse
	(*RequestJobRequest)(nil),      // 10: compute.v1.RequestJobRequest
	(*RequestJobResponse)(nil),     // 11: compute.v1.RequestJobResponse
	(*SubmitResultRequest)(nil),    // 12: compute.v1.SubmitResultRequest
	(*SubmitResultResponse)(nil),   // 13: compute.v1.SubmitResultResponse
}
var file_worker_proto_depIdxs = []int32{
	2,  // 0: compute.v1.Job.job_id:type_name -> compute.v1.JobID
	3,  // 1: compute.v1.Job.required_resources:type_name -> compute.v1.ResourceSpec
	0,  // 2: compute.v1.Job.status:type_name -> compute.v1.Status
	2,  // 3: compute.v1.Result.job_id:type_name -> compute.v1.JobID
	0,  // 4: compute.v1.Result.status:type_name -> compute.v1.Status
	3,  // 5: compute.v1.RegisterWorkerRequest.available_resources:type_name -> compute.v1.ResourceSpec
	1,  // 6: compute.v1.RegisterWorkerResponse.worker_id:type_name -> compute.v1.WorkerID
	1,  // 7: compute.v1.HeartbeatRequest.worker_id:type_name -> compute.v1.WorkerID
	3,  // 8: compute.v1.HeartbeatRequest.available_resources:type_name -> compute.v1.ResourceSpec
	2,  // 9: compute.v1.HeartbeatRequest.running_jobs:type_name -> compute.v1.JobID
	1,  // 10: compute.v1.RequestJobRequest.worker_id:type_name -> compute.v1.WorkerID
	4,  // 11: compute.v1.RequestJobResponse.job:type_name -> compute.v1.Job
	1,  // 12: compute.v1.SubmitResultRequest.worker_id:type_name -> compute.v1.WorkerID
	5,  // 13: compute.v1.SubmitResultRequest.result:type_name -> compute.v1.Result
	6,  // 14: compute.v1.WorkerService.RegisterWorker:input_type -> compute.v1.RegisterWorkerRequest
	8,  // 15: compute.v1.WorkerService.Heartbeat:input_type -> compute.v1.HeartbeatRequest
	10, // 16: compute.v1.WorkerService.RequestJob:input_type -> compute.v1.RequestJobRequest
	12, // 17: compute.v1.WorkerService.SubmitResult:input_type -> compute.v1.SubmitResultRequest
	7,  // 18: compute.v1.WorkerService.RegisterWorker:output_type -> compute.v1.RegisterWorkerResponse
	9,  // 19: compute.v1.WorkerService.Heartbeat:output_type -> compute.v1.HeartbeatResponse
	11, // 20: compute.v1.WorkerService.RequestJob:output_type -> compute.v1.RequestJobResponse
	13, // 21: compute.v1.WorkerService.SubmitResult:output_type -> compute.v1.SubmitResultResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
